### ISSUE TITLE
compatibility with haros update

### ISSUE THREAD

**Issue by aremazeilles** [ipa320/ros-model#106]
Runnning the model analysis with the docker:

```
docker run -p 4000:80 -ti haros:latest /haros_runner.sh https://github.com/aremazeilles/dummy_package.git dummy_package dummy_node
```

I get the following error:

```
[100%] Built target dummy_node
Traceback (most recent call last):
  File "/ros_model_extractor.py", line 207, in <module>
    main()
  File "/ros_model_extractor.py", line 202, in main
    if extractor.launch():
  File "/ros_model_extractor.py", line 78, in launch
    self.extract_primitives(node, parser.global_scope, analysis, rosmodel)
  File "/ros_model_extractor.py", line 91, in extract_primitives
    name = analysis._extract_topic(call)
AttributeError: 'NodeExtractor' object has no attribute '_extract_topic'
``` 

I am not sure when was updated the pip package of haros, but in the current version of file [extractor.py](https://github.com/git-afsantos/haros/blob/master/haros/extractor.py), the requested method is now in classes `RospyExtractor` and `RoscppExtractor`

**Comment by ipa-nhg** [comment]
closed, see https://github.com/ipa320/ros-model/issues/105#issuecomment-636055729 for further details.

Code also moved to [ros-model-cloud](https://github.com/ipa320/ros-model-cloud), new issue -> https://github.com/ipa320/ros-model-cloud/issues/35
