### ISSUE TITLE
Assign hardware port to docker-compose file 

### ISSUE THREAD

**Issue by ipa-rwu** [ipa320/ros-model#158]
@ipa-nhg 
To connect hardware with docker container, we also need to assign hardware port to docker container, e.g. 
`docker run --rm -it --device=/dev/input/js1 --device=/dev/jackal  rachelwu/agriculture_demo_sprint2:agriculture_demo_sprint2`

Some of ports are also assigned in [launch file](https://github.com/jackal/jackal/blob/melodic-devel/jackal_control/launch/teleop.launch#L2), e.g.
` <arg name="joy_dev" default="$(optenv JACKAL_JOY_DEVICE /dev/input/ps4)" />`

I propose to generate a docker-compose file also for rossystem(without ComponentStack). So we can assign a port like:
```
devices:
  - "/dev/input/js1:/dev/input/js1"
```
But there is an issue: how can I get this information from model level?

**Comment by ipa-nhg** [comment]
From my point of view, this information should be part of a new "deployment" model but from of the "rossystem" model. The Rossystem model is independent of the machine where the software will be deployed.

This new deployment model should also contain information about the machine, the OS, the distro... @ipa-rwu what do you think?

**Comment by ipa-rwu** [comment]
Yes, I like this idea.
