### ISSUE TITLE
Package name in setup.py is wrong for stacks in ros2 version

### ISSUE THREAD

**Issue by ipa-rwu** [ipa320/ros-model#171]
The Package name in setup.py is not as same as package name in package.xml.
It only uses system name in setup.py

I also suggest adding "_ros2" for each stack package in order to not mix with ros1 version.

**Comment by ipa-nhg** [comment]
The name of the package is the same for package.xml and for setup.py, without the suffix "_ros2". The only difference there is that the folder that contains the package has another name (i.e., we add then the suffix _ros2 to do not overwrite the code generated for ROS1 packages).

See:https://github.com/ipa320/ros-model/blob/master/plugins/de.fraunhofer.ipa.rossystem.xtext/src/de/fraunhofer/ipa/rossystem/generator/PackageXmlCompiler.xtend#L44 and https://github.com/ipa320/ros-model/blob/master/plugins/de.fraunhofer.ipa.rossystem.xtext/src/de/fraunhofer/ipa/rossystem/generator/SetupPyCompiler.xtend#L16 

Am I missing anything?

what looks like missed is the support of stacks for the setup.py generator. I will check it out.
