### ISSUE TITLE
launch file extension need to be ".launch.py" for ros2

### ISSUE THREAD

**Issue by ipa-rwu** [ipa320/ros-model#172]
When I try to build packages in docker image (ros:foxy-ros-core), colcon build can't put launch file with extension (.launch or .py) into install space. It must be ".launch.py"

**Comment by ipa-nhg** [comment]
Thanks for finding this issue, you are right the setup.py  generator looks for files with the extension .launch.py (see https://github.com/ipa320/ros-model/blob/master/plugins/de.fraunhofer.ipa.rossystem.xtext/src/de/fraunhofer/ipa/rossystem/generator/SetupPyCompiler.xtend#L29) and we are generating .launch files (https://github.com/ipa320/ros-model/blob/master/plugins/de.fraunhofer.ipa.rossystem.xtext/src/de/fraunhofer/ipa/rossystem/generator/RosSystemGenerator.xtend#L101). I will fix it and send a new PR.
