### ISSUE TITLE
Should not generate system package when using stacks in ros2

### ISSUE THREAD

**Issue by ipa-rwu** [ipa320/ros-model#173]
When I create a system with stacks, the tooling creates a whole system package which includes stack packages.

It can create a meta-package but stack packages should not be inside this folder. 

![image](https://user-images.githubusercontent.com/54799760/141438703-decb8f61-ecc9-466d-8aed-bad5dd4bc8c7.png)

For stack package, the "__init__.py" should be in a folder.
![image](https://user-images.githubusercontent.com/54799760/141438883-21ccff35-be93-4812-ac97-b7d33e48b077.png)

**Comment by ipa-nhg** [comment]
Good point, I never consider this issue. I will try to fix it! Thanks for reporting 😄

**Comment by ipa-nhg** [comment]
I can't reproduce your filesystem structure. For this exmaple model:

```
RosSystem { Name 'demo_with_stacks'  
	RosComponentStacks (
		ComponentStack { name base
			RosComponents (
			     ComponentInterface { name jackal_node FromRosNode "jackal_base.jackal_node.jackal_node" },
			     ComponentInterface { name nmea_topic_driver NameSpace navsat FromRosNode "nmea_navsat_driver.nmea_topic_driver.nmea_topic_driver" } ,
			     ComponentInterface { name  controller_spawner FromRosNode "controller_manager.spawner.controller_spawner" })},
		ComponentStack { name teleop 
			RosComponents (
			     ComponentInterface { name twist_mux FromRosNode "twist_mux.twist_mux.twist_mux" },
			     ComponentInterface { name joy_node NameSpace bluetooth_teleop FromRosNode "joy.joy_node.joy_node" },
			     ComponentInterface { name teleop_twist_joy NameSpace bluetooth_teleop FromRosNode "teleop_twist_joy.teleop_node.teleop_node" } , 
			     ComponentInterface { name twist_marker_server FromRosNode "interactive_marker_twist_server.marker_server.twist_marker_server"})},
		ComponentStack { name others 
			RosComponents (
			     ComponentInterface { name  imu_filter FromRosNode "imu_filter_madgwick.imu_filter_node.imu_filter_node" } ,
			     ComponentInterface { name  ekf_localization FromRosNode "robot_localization.ekf_localization_node.ekf_localization_node" })}
)}
```


I get the following structure:

![image](https://user-images.githubusercontent.com/650568/141466989-5a16226f-3716-4b2e-b734-2dc413682ac0.png)

**Comment by ipa-rwu** [comment]
I forget to mention that I tried it on ros2

**Comment by ipa-rwu** [comment]
Sorry, it is my bad. I forget remove src-gen first. So it was mixed.
