### ISSUE TITLE
Fix validation error: Missing packages/wrong versions

### ISSUE THREAD

**Issue by ipa-nhg** [ipa320/ros-model#77]
I get the following error when I start the ROS tooling by https://github.com/ipa320/ros-model#0-start-the-ros-tooling-application

![image](https://user-images.githubusercontent.com/650568/65584482-3edda880-df81-11e9-84ce-0404b11c47ca.png)

**Comment by roman-pr94** [comment]
Dear developers,I get the same issue with

**Comment by ipa-nhg** [comment]
Fixed by https://github.com/ipa320/ros-model/pull/90
