### ISSUE TITLE
Fix error "modify resource" by creating a new project

### ISSUE THREAD

**Issue by ipa-nhg** [ipa320/ros-model#79]
I get the following error:

![image](https://user-images.githubusercontent.com/650568/65589043-b6fb9c80-df88-11e9-9b79-f0ac3b3db228.png)

By: https://github.com/ipa320/ros-model/blob/master/docu/NewProject.md

It has to be related to the auto generation of the representation file https://github.com/ipa320/ros-model/commit/a4972e09276358310fc653873f9927eaca1888c0#diff-da4fc5d06072a4c1892f7d540b943ce8

**Comment by ipa-nhg-ha** [comment]
I created new project on my PC and it is not giving me any error. 
Thanks.
