### ISSUE TITLE
Subsystem not refreshing

### ISSUE THREAD

**Issue by duda1202** [ipa320/ros-model#95]
Hi,

I have used your tutorial to create a subsystem for the lasers and then create a full system using that subsystem inside it. However, when I change something on the subsystem, it does not update/refresh on the system. Is there anyway this can be done or is it not possible at the moment?

**Comment by ipa-nhg** [comment]
Hi,

unfortunately this is not possible at the moment: by importing a ComponentInterface this will be copied as fix subsystem of my new system and its update doesn't change the system. The only solution now is remove the subsystem and import it again.

Please keep the issue open, will address this as soon as possible. 

Thanks and sorry for the inconveniences!

**Comment by ipa-nhg** [comment]
I updated the models to define the root ROS package for each component that forms a system, I have added also a new button that  can be triggered to automatically refresh the interfaces of a system in case the root ROS package was modified.

Code changes:https://github.com/ipa320/ros-model/pull/124
This new feature will be part of the next Release of the tooling
